<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <title>Research – bart</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-0fde88a82f0356838740f155f1088782.css">
  <link rel="stylesheet" href="custom.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="mental-fatigue-and-decision-making" class="slide level2 center">
<h2>Mental fatigue and decision making</h2>
</section>
<section id="introduction-background" class="title-slide slide level1 scrollable">
<h1>Introduction / Background</h1>
<ol type="1">
<li class="fragment"><p>Mental fatigue can impair core executive functions</p></li>
<li class="fragment"><p>Decision making as executive function. Important aspect of decision making is risk taking.</p></li>
<li class="fragment"><p>Does mental fatigue impair risk taking?</p></li>
<li class="fragment"><p>Initial evidence that it does,</p></li>
<li class="fragment"><p>But there is no standard protocol for inducing a transient state of mental fatigue, and (TO DO: check if true) individual working memory capacity not accounted</p></li>
<li class="fragment"><p>This study will uses</p></li>
</ol>
<ol type="a">
<li class="fragment">recently developed protocol to induce two types of mental fatigue based on small but impactful tweaks of the same activity (Stroop task)</li>
<li class="fragment">BART to evaluate risk taking</li>
<li class="fragment">well established complex span tasks to measure working memory capacity, as ability to maintain information in spite of interfering processing</li>
<li class="fragment">self report measures throughout of mental fatigue and associated concepts (sleepiness, boredom, workload)</li>
</ol>
<ol start="6" type="1">
<li class="fragment"><p>Previous evidence that computerized (and individualized) fatiguing protocols are effective and induce comparable self-report mental fatigue. Interestingly, despite the similar emntal fatigue, they achieve mental fatigue through different paths (overload, underload)</p></li>
<li class="fragment"><p>Objectives:</p></li>
</ol>
<ol type="a">
<li class="fragment">further evaluation of the fatiguing protocol</li>
<li class="fragment">does mental fatigue influence risk taking?</li>
<li class="fragment">does working memory moderate this influence?</li>
</ol>
</section>

<section id="method" class="title-slide slide level1 scrollable">
<h1>Method</h1>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Participants</strong> 36 sport science students (18+ years old)</p>
<p><strong>Design:</strong> Experimental within-subject study. All participants completed risk taking evaluation at baseline (i.e., no fatigue) and then after computerized activities designed to induce either underload fatigue and overload fatigue. Participation involved two days, one for the underload fatigue, and the other for the overload fatigue, in counterbalanced order. Baseline evaluation occurred either on the first or second day, counterbalanced, whereas on the other day, we evaluated participants’ pre-fatigue working memory capacity.</p>
</div><div class="column" style="width:50%;">
<p><strong>Procedure:</strong></p>
<p>Two visits per participant, each lasting ca. XXX minutes.</p>
<div class="cell" data-fig-width="6" data-fig-height="6" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<svg width="576" height="576" viewbox="0.00 0.00 604.17 825.14" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none; display: block; margin: auto auto auto auto">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 821.14)">
<title>protocol</title>
<g id="clust1" class="cluster">
<title>cluster_0</title>
<polygon fill="lightgrey" stroke="lightgrey" points="74.49,-304 74.49,-433.14 528.49,-433.14 528.49,-304 74.49,-304"></polygon>
</g>
<!-- A -->
<g id="node1" class="node">
<title>A</title>
<text text-anchor="middle" x="296.49" y="-786.14" font-family="Times,serif" font-size="30.00">demographics</text>
</g>
<!-- B -->
<g id="node2" class="node">
<title>B</title>
<polygon fill="lightblue" stroke="lightblue" points="143.49,-737.14 0.01,-657.14 143.49,-577.14 286.96,-657.14 143.49,-737.14"></polygon>
<text text-anchor="middle" x="143.49" y="-666.14" font-family="Times,serif" font-size="30.00">risk taking</text>
<text text-anchor="middle" x="143.49" y="-630.14" font-family="Times,serif" font-size="30.00">(baseline)</text>
</g>
<!-- A&#45;&gt;B -->
<g id="edge1" class="edge">
<title>A-&gt;B</title>
<path fill="none" stroke="black" d="M272.58,-772.89C254.68,-756.98 229.34,-734.45 205.84,-713.57"></path>
<polygon fill="black" stroke="black" points="208.09,-710.88 198.29,-706.85 203.44,-716.11 208.09,-710.88"></polygon>
</g>
<!-- C -->
<g id="node3" class="node">
<title>C</title>
<polygon fill="none" stroke="black" points="596.35,-657.14 523.42,-692.99 377.55,-692.99 304.62,-657.14 377.55,-621.29 523.42,-621.29 596.35,-657.14"></polygon>
<text text-anchor="middle" x="450.49" y="-648.14" font-family="Times,serif" font-size="30.00">WM capacity</text>
</g>
<!-- A&#45;&gt;C -->
<g id="edge2" class="edge">
<title>A-&gt;C</title>
<path fill="none" stroke="black" d="M320.55,-772.89C342.59,-753.43 375.84,-724.06 403.18,-699.91"></path>
<polygon fill="black" stroke="black" points="405.55,-702.49 410.73,-693.25 400.91,-697.24 405.55,-702.49"></polygon>
</g>
<!-- D -->
<g id="node4" class="node">
<title>D</title>
<polygon fill="lightgray" stroke="lightgray" points="404.07,-541.14 188.9,-541.14 188.9,-461.14 404.07,-461.14 404.07,-541.14"></polygon>
<text text-anchor="middle" x="296.49" y="-510.14" font-family="Times,serif" font-size="30.00">state self-reports</text>
<text text-anchor="middle" x="296.49" y="-474.14" font-family="Times,serif" font-size="30.00">(pre fatigue)</text>
</g>
<!-- B&#45;&gt;D -->
<g id="edge3" class="edge">
<title>B-&gt;D</title>
<path fill="none" stroke="black" d="M194.01,-605.28C212.13,-587.04 232.47,-566.57 250.22,-548.71"></path>
<polygon fill="black" stroke="black" points="253.08,-550.79 257.65,-541.23 248.12,-545.85 253.08,-550.79"></polygon>
</g>
<!-- C&#45;&gt;D -->
<g id="edge4" class="edge">
<title>C-&gt;D</title>
<path fill="none" stroke="black" d="M415.54,-621.19C393.99,-599.64 366.09,-571.74 342.72,-548.37"></path>
<polygon fill="black" stroke="black" points="345.17,-545.87 335.63,-541.28 340.22,-550.82 345.17,-545.87"></polygon>
</g>
<!-- E -->
<g id="node5" class="node">
<title>E</title>
<ellipse fill="white" stroke="white" cx="410.49" cy="-368.57" rx="110.03" ry="56.64"></ellipse>
<text text-anchor="middle" x="410.49" y="-377.57" font-family="Times,serif" font-size="30.00">fatigue</text>
<text text-anchor="middle" x="410.49" y="-341.57" font-family="Times,serif" font-size="30.00">(underload)</text>
</g>
<!-- D&#45;&gt;E -->
<g id="edge5" class="edge">
<title>D-&gt;E</title>
<path fill="none" stroke="black" d="M330.69,-460.96C339.64,-450.71 349.49,-439.43 359.13,-428.39"></path>
<polygon fill="black" stroke="black" points="361.81,-430.64 365.75,-420.81 356.53,-426.04 361.81,-430.64"></polygon>
</g>
<!-- F -->
<g id="node6" class="node">
<title>F</title>
<ellipse fill="white" stroke="white" cx="182.49" cy="-368.57" rx="99.81" ry="56.64"></ellipse>
<text text-anchor="middle" x="182.49" y="-377.57" font-family="Times,serif" font-size="30.00">fatigue</text>
<text text-anchor="middle" x="182.49" y="-341.57" font-family="Times,serif" font-size="30.00">(overload)</text>
</g>
<!-- D&#45;&gt;F -->
<g id="edge6" class="edge">
<title>D-&gt;F</title>
<path fill="none" stroke="black" d="M262.28,-460.96C253.12,-450.46 243.01,-438.89 233.16,-427.61"></path>
<polygon fill="black" stroke="black" points="235.61,-425.09 226.39,-419.86 230.33,-429.69 235.61,-425.09"></polygon>
</g>
<!-- G -->
<g id="node7" class="node">
<title>G</title>
<polygon fill="lightgray" stroke="lightgray" points="404.07,-276 188.9,-276 188.9,-196 404.07,-196 404.07,-276"></polygon>
<text text-anchor="middle" x="296.49" y="-245" font-family="Times,serif" font-size="30.00">state self-reports</text>
<text text-anchor="middle" x="296.49" y="-209" font-family="Times,serif" font-size="30.00">(post fatigue)</text>
</g>
<!-- E&#45;&gt;G -->
<g id="edge7" class="edge">
<title>E-&gt;G</title>
<path fill="none" stroke="black" d="M366.08,-316.71C356.63,-305.88 346.68,-294.49 337.36,-283.82"></path>
<polygon fill="black" stroke="black" points="339.92,-281.42 330.7,-276.19 334.64,-286.03 339.92,-281.42"></polygon>
</g>
<!-- F&#45;&gt;G -->
<g id="edge8" class="edge">
<title>F-&gt;G</title>
<path fill="none" stroke="black" d="M226.23,-317.46C235.83,-306.47 245.97,-294.86 255.45,-283.99"></path>
<polygon fill="black" stroke="black" points="258.29,-286.06 262.23,-276.23 253.02,-281.46 258.29,-286.06"></polygon>
</g>
<!-- H -->
<g id="node8" class="node">
<title>H</title>
<polygon fill="lightblue" stroke="lightblue" points="296.49,-160 119.92,-80 296.49,0 473.05,-80 296.49,-160"></polygon>
<text text-anchor="middle" x="296.49" y="-89" font-family="Times,serif" font-size="30.00">risk taking</text>
<text text-anchor="middle" x="296.49" y="-53" font-family="Times,serif" font-size="30.00">(post fatigue)</text>
</g>
<!-- G&#45;&gt;H -->
<g id="edge9" class="edge">
<title>G-&gt;H</title>
<path fill="none" stroke="black" d="M296.49,-195.74C296.49,-187.78 296.49,-179.1 296.49,-170.19"></path>
<polygon fill="black" stroke="black" points="299.99,-170.07 296.49,-160.07 292.99,-170.08 299.99,-170.07"></polygon>
</g>
</g>
</svg>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div></div>
<p><strong>Induction of mental fatigue</strong> Description of the two tasks: congruent Stroop and go/nogo Stroop TO DO</p>
<p><strong>Working memory capacity</strong> TO DO</p>
<p><strong>Evaluation of risk taking</strong> Description of BART TO DO - Competitive incentive: top 3 scorers receive cash prizes (£30, £15, £5).</p>
<p><strong>Open Science:</strong> - BART (available at repository: https://github.com/GermanoGallicchio/BART) - Fatiguing tasks (available at repository: TO DO) - Working memory capacity (available at repository: TO DO) - recording and analysis based on: https://englelab.gatech.edu/articles/2005/working-memory-span-tasks-a-methodological-review-and-user27s-guide.pdf - data to be uploaded to osf (TO DO) - code to be uploaded to osf (TO DO)</p>
</section>

<section id="objectiveshypotheses-analyses-results-1" class="title-slide slide level1 scrollable">
<h1>Objectives/hypotheses, analyses, results #1</h1>
<p>Data-driven hypotheses:</p>
<ul>
<li class="fragment">1.1 Our two manipulations successfully induced increased mental fatigue over time</li>
<li class="fragment">1.2 Sleepiness and …</li>
<li class="fragment">1.3 …boredom would also increase over time, but more for the underload than overload</li>
</ul>
<p>Exploratory hypotheses:</p>
<ul>
<li class="fragment">The previous results would be moderated by working memory capacacity, whereby
<ul>
<li class="fragment">1.1b the increase in mental fatigue would be steeper for those with smaller working memory capacity, at least for the overload condition</li>
<li class="fragment">1.2 b</li>
<li class="fragment">1.3 b</li>
</ul></li>
</ul>
<p><img src="bart_files/analysis1.png" style="max-width: 100%; height: auto;"></p>
<p>Analyses:</p>
<ul>
<li class="fragment">linear mixed models (R, lmer, lmerTest)</li>
<li class="fragment">categorical variable contrasts:
<ul>
<li class="fragment">condition: a two-level variable (0=underload, 1=overload)</li>
<li class="fragment">time: a four level variable (post25, post50, post75, post100) with polynomial contrasts for linear, quadratic, and cubic trends</li>
</ul></li>
<li class="fragment">working memory capacity mean centered</li>
</ul>
<p>Formulas and Results</p>
<p>1.1 Mental fatigue</p>
<pre><code>mod1 = lmer(MF ~ condition * stage + MF_pre + (1 + condition | subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                          Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)                41.8017     5.0881  63.6963   8.216 1.39e-11 ***
conditionoverload           4.2047     3.8939  34.6871   1.080    0.288    
stage.L                    25.2742     2.1448 210.0000  11.784  &lt; 2e-16 ***
stage.Q                    -9.0912     2.1448 210.0000  -4.239 3.37e-05 ***
stage.C                     1.2126     2.1448 210.0000   0.565    0.572    
MF_pre                      0.8170     0.1601  59.6055   5.102 3.68e-06 ***
conditionoverload:stage.L  -1.9945     3.0331 210.0000  -0.658    0.512    
conditionoverload:stage.Q   3.0997     3.0331 210.0000   1.022    0.308    
conditionoverload:stage.C  -1.9922     3.0331 210.0000  -0.657    0.512   </code></pre>
<p>1.1b Mental fatigue</p>
<pre><code>mod2 = lmer(MF ~ condition * stage * WMC_partial_unit_centered +  MF_pre + (1 + condition | subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                                    Estimate Std. Error      df
(Intercept)                                           41.989      5.183  62.304
conditionoverload                                      4.212      3.949  33.669
stage.L                                               25.274      2.133 204.000
stage.Q                                               -9.091      2.133 204.000
stage.C                                                1.213      2.133 204.000
WMC_partial_unit_centered                            -17.136     54.797  32.119
MF_pre                                                 0.809      0.164  56.881
conditionoverload:stage.L                             -1.994      3.016 204.000
conditionoverload:stage.Q                              3.100      3.016 204.000
conditionoverload:stage.C                             -1.992      3.016 204.000
conditionoverload:WMC_partial_unit_centered           15.523     62.081  33.725
stage.L:WMC_partial_unit_centered                     24.296     33.491 204.000
stage.Q:WMC_partial_unit_centered                    -30.808     33.491 204.000
stage.C:WMC_partial_unit_centered                     34.221     33.491 204.000
conditionoverload:stage.L:WMC_partial_unit_centered  -94.816     47.364 204.000
conditionoverload:stage.Q:WMC_partial_unit_centered   45.046     47.364 204.000
conditionoverload:stage.C:WMC_partial_unit_centered    4.741     47.364 204.000
                                                    t value Pr(&gt;|t|)    
(Intercept)                                           8.101 2.56e-11 ***
conditionoverload                                     1.067   0.2937    
stage.L                                              11.851  &lt; 2e-16 ***
stage.Q                                              -4.263 3.08e-05 ***
stage.C                                               0.569   0.5703    
WMC_partial_unit_centered                            -0.313   0.7565    
MF_pre                                                4.932 7.43e-06 ***
conditionoverload:stage.L                            -0.661   0.5092    
conditionoverload:stage.Q                             1.028   0.3053    
conditionoverload:stage.C                            -0.661   0.5096    
conditionoverload:WMC_partial_unit_centered           0.250   0.8041    
stage.L:WMC_partial_unit_centered                     0.725   0.4690    
stage.Q:WMC_partial_unit_centered                    -0.920   0.3587    
stage.C:WMC_partial_unit_centered                     1.022   0.3081    
conditionoverload:stage.L:WMC_partial_unit_centered  -2.002   0.0466 *  
conditionoverload:stage.Q:WMC_partial_unit_centered   0.951   0.3427    
conditionoverload:stage.C:WMC_partial_unit_centered   0.100   0.9204    </code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">baseline mental fatigue is positively associated with mental fatigue experienced at later stages, whereby individuals starting with a larger score reported larger scores for the later stages</li>
<li class="fragment">positive liner and negative quadratic trends for underload indicating overall increase with levelling off (inverted-U)</li>
<li class="fragment">trends were not different for overload</li>
<li class="fragment">when including working memory capacity as predictor:
<ul>
<li class="fragment">the effects described above persist</li>
<li class="fragment">in addition, for individuals with greater working memory capacity the linear increase in mental fatigue over time in the overload condition is less steep (i.e., having greater working memory capacity attenuates the increase in mental fatigue over time for the overload activity)</li>
</ul></li>
</ul>
<p>1.2 Sleepiness</p>
<pre><code>mod1 = lmer(KSS ~ condition * stage + KSS_pre + (1 + condition | subjID), data = data)</code></pre>
<pre><code>                           Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept)                 4.07775    0.56174  68.70279   7.259 4.60e-10 ***
conditionoverload          -0.34233    0.36547  34.52807  -0.937   0.3554    
stage.L                     2.26712    0.17833 210.00000  12.713  &lt; 2e-16 ***
stage.Q                    -0.95833    0.17833 210.00000  -5.374 2.04e-07 ***
stage.C                     0.09317    0.17833 210.00000   0.522   0.6019    
KSS_pre                     0.69126    0.14929  66.10582   4.630 1.76e-05 ***
conditionoverload:stage.L  -0.52796    0.25220 210.00000  -2.093   0.0375 *  
conditionoverload:stage.Q   0.23611    0.25220 210.00000   0.936   0.3502    
conditionoverload:stage.C   0.09317    0.25220 210.00000   0.369   0.7122   </code></pre>
<p>1.2b Sleepiness</p>
<pre><code>mod2 = lmer(KSS ~ condition * stage * WMC_partial_unit_centered + KSS_pre + (1 + condition | subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                                     Estimate Std. Error
(Intercept)                                           4.15371    0.56991
conditionoverload                                    -0.34043    0.36999
stage.L                                               2.26712    0.17634
stage.Q                                              -0.95833    0.17634
stage.C                                               0.09317    0.17634
WMC_partial_unit_centered                            -3.79133    4.12103
KSS_pre                                               0.66847    0.15211
conditionoverload:stage.L                            -0.52796    0.24939
conditionoverload:stage.Q                             0.23611    0.24939
conditionoverload:stage.C                             0.09317    0.24939
conditionoverload:WMC_partial_unit_centered           3.04124    5.84068
stage.L:WMC_partial_unit_centered                     6.69506    2.76927
stage.Q:WMC_partial_unit_centered                    -4.48221    2.76927
stage.C:WMC_partial_unit_centered                     3.51446    2.76927
conditionoverload:stage.L:WMC_partial_unit_centered  -8.56888    3.91634
conditionoverload:stage.Q:WMC_partial_unit_centered   5.24308    3.91634
conditionoverload:stage.C:WMC_partial_unit_centered  -2.43602    3.91634
                                                           df t value Pr(&gt;|t|)
(Intercept)                                          66.72236   7.288 4.70e-10
conditionoverload                                    33.50335  -0.920   0.3641
stage.L                                             204.00005  12.856  &lt; 2e-16
stage.Q                                             204.00005  -5.434 1.56e-07
stage.C                                             204.00005   0.528   0.5978
WMC_partial_unit_centered                            32.86828  -0.920   0.3643
KSS_pre                                              64.06978   4.395 4.26e-05
conditionoverload:stage.L                           204.00005  -2.117   0.0355
conditionoverload:stage.Q                           204.00005   0.947   0.3449
conditionoverload:stage.C                           204.00005   0.374   0.7091
conditionoverload:WMC_partial_unit_centered          33.86378   0.521   0.6060
stage.L:WMC_partial_unit_centered                   204.00005   2.418   0.0165
stage.Q:WMC_partial_unit_centered                   204.00005  -1.619   0.1071
stage.C:WMC_partial_unit_centered                   204.00005   1.269   0.2059
conditionoverload:stage.L:WMC_partial_unit_centered 204.00005  -2.188   0.0298
conditionoverload:stage.Q:WMC_partial_unit_centered 204.00005   1.339   0.1821
conditionoverload:stage.C:WMC_partial_unit_centered 204.00005  -0.622   0.5346
                                                       
(Intercept)                                         ***
conditionoverload                                      
stage.L                                             ***
stage.Q                                             ***
stage.C                                                
WMC_partial_unit_centered                              
KSS_pre                                             ***
conditionoverload:stage.L                           *  
conditionoverload:stage.Q                              
conditionoverload:stage.C                              
conditionoverload:WMC_partial_unit_centered            
stage.L:WMC_partial_unit_centered                   *  
stage.Q:WMC_partial_unit_centered                      
stage.C:WMC_partial_unit_centered                      
conditionoverload:stage.L:WMC_partial_unit_centered *  
conditionoverload:stage.Q:WMC_partial_unit_centered    
conditionoverload:stage.C:WMC_partial_unit_centered                                                              </code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">baseline sleepiness is positively associated with sleepiness experienced at later stages, whereby individuals starting with a larger score reported larger scores for the later stages</li>
<li class="fragment">positive linear and negative quadratic trends for underload indicating overall increase with levelling off (inverted-U)</li>
<li class="fragment">the linear increase over time was less steep for overload than underload</li>
<li class="fragment">when including working memory capacity as predictor:
<ul>
<li class="fragment">the effects described above persist, with similar magnitude</li>
<li class="fragment">in addition, for people with greater working memory capacity the linear increase in sleepiness over time in the underload condition becomes steeper, and less steep for overload. (i.e., having a high working memory capacity amplifies the linear trend but only for underload, whereas it attenuates the linear trend for overload)</li>
</ul></li>
</ul>
<p>1.3 Boredom</p>
<pre><code>mod1 = lmer(boredom ~ condition * stage + boredom_pre + (1 + condition | subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                          Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)                59.9432     4.4290  52.3289  13.534  &lt; 2e-16 ***
conditionoverload         -10.6546     5.0493  34.8972  -2.110  0.04209 *  
stage.L                    22.0839     2.4009 210.0000   9.198  &lt; 2e-16 ***
stage.Q                   -10.6667     2.4009 210.0000  -4.443 1.44e-05 ***
stage.C                     2.2981     2.4009 210.0000   0.957  0.33959    
boredom_pre                 0.4529     0.1344  61.0536   3.371  0.00131 ** 
conditionoverload:stage.L  -7.5500     3.3954 210.0000  -2.224  0.02724 *  
conditionoverload:stage.Q   8.0855     3.3954 210.0000   2.381  0.01814 *  
conditionoverload:stage.C  -3.3718     3.3954 210.0000  -0.993  0.32184    </code></pre>
<p>1.3b Boredom</p>
<pre><code>mod2 = lmer(boredom ~ condition * stage * WMC_partial_unit_centered + boredom_pre + (1 + condition | subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                                    Estimate Std. Error
(Intercept)                                          59.5072     4.5329
conditionoverload                                   -10.6793     5.0059
stage.L                                              22.0839     2.3705
stage.Q                                             -10.6667     2.3705
stage.C                                               2.2981     2.3705
WMC_partial_unit_centered                             8.2501    42.9278
boredom_pre                                           0.4693     0.1382
conditionoverload:stage.L                            -7.5500     3.3523
conditionoverload:stage.Q                             8.0855     3.3523
conditionoverload:stage.C                            -3.3718     3.3523
conditionoverload:WMC_partial_unit_centered          99.1394    79.4383
stage.L:WMC_partial_unit_centered                    88.1928    37.2253
stage.Q:WMC_partial_unit_centered                   -53.3034    37.2253
stage.C:WMC_partial_unit_centered                    33.6813    37.2253
conditionoverload:stage.L:WMC_partial_unit_centered -29.7008    52.6445
conditionoverload:stage.Q:WMC_partial_unit_centered  29.4033    52.6445
conditionoverload:stage.C:WMC_partial_unit_centered -24.1012    52.6445
                                                          df t value Pr(&gt;|t|)
(Intercept)                                          53.6076  13.128  &lt; 2e-16
conditionoverload                                    33.8786  -2.133   0.0402
stage.L                                             204.0000   9.316  &lt; 2e-16
stage.Q                                             204.0000  -4.500 1.14e-05
stage.C                                             204.0000   0.969   0.3335
WMC_partial_unit_centered                            35.1361   0.192   0.8487
boredom_pre                                          61.8104   3.397   0.0012
conditionoverload:stage.L                           204.0000  -2.252   0.0254
conditionoverload:stage.Q                           204.0000   2.412   0.0168
conditionoverload:stage.C                           204.0000  -1.006   0.3157
conditionoverload:WMC_partial_unit_centered          34.7318   1.248   0.2204
stage.L:WMC_partial_unit_centered                   204.0000   2.369   0.0188
stage.Q:WMC_partial_unit_centered                   204.0000  -1.432   0.1537
stage.C:WMC_partial_unit_centered                   204.0000   0.905   0.3666
conditionoverload:stage.L:WMC_partial_unit_centered 204.0000  -0.564   0.5733
conditionoverload:stage.Q:WMC_partial_unit_centered 204.0000   0.559   0.5771
conditionoverload:stage.C:WMC_partial_unit_centered 204.0000  -0.458   0.6476
                                                       
(Intercept)                                         ***
conditionoverload                                   *  
stage.L                                             ***
stage.Q                                             ***
stage.C                                                
WMC_partial_unit_centered                              
boredom_pre                                         ** 
conditionoverload:stage.L                           *  
conditionoverload:stage.Q                           *  
conditionoverload:stage.C                              
conditionoverload:WMC_partial_unit_centered            
stage.L:WMC_partial_unit_centered                   *  
stage.Q:WMC_partial_unit_centered                      
stage.C:WMC_partial_unit_centered                      
conditionoverload:stage.L:WMC_partial_unit_centered    
conditionoverload:stage.Q:WMC_partial_unit_centered    
conditionoverload:stage.C:WMC_partial_unit_centered    </code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">baseline boredom is positively associated with foredom experienced at later stages, whereby individuals starting with a larger score reported larger scores for the later stages</li>
<li class="fragment">underload condition was perceived as more boring than the overload</li>
<li class="fragment">positive linear and negative quadratic trends for underload indicating overall increase with levelling off (inverted-U)</li>
<li class="fragment">the linear increase over time was less steep for overload than underload; the quadratic trend was also less pronounced for overload</li>
<li class="fragment">when including working memory capacity as predictor:
<ul>
<li class="fragment">the effects described above persist, with similar magnitude</li>
<li class="fragment">in addition, for people with greater working memory capacity the linear increase in boredom over time for underload becomes steeper (with no difference in steepiness for overload). (i.e., having greater working memory capacity amplifies the linear increase over time for underload and no evidence of different effect for overload)</li>
</ul></li>
</ul>
</section>

<section id="objectiveshypotheses-analyses-results-1-cont" class="title-slide slide level1 scrollable">
<h1>Objectives/hypotheses, analyses, results #1 cont</h1>
<p>Data-driven hypotheses:</p>
<ul>
<li class="fragment">1.4 Overload activity would be associated with greater workload than underload</li>
<li class="fragment">1.5 Both activities would have larger ratings for mental demands (etc) than physical demands, and this difference would be larger for overload</li>
</ul>
<p>Exploratory hypotheses</p>
<ul>
<li class="fragment">The previous effects would be more pronounced for people with lower working memory capacity, but just in the overload activity (i.e., those with lower working memory capacity rate the go-nogo task as more difficult)</li>
</ul>
<p>Figure: overall workload</p>
<p><img src="bart_files/analysis3.png" style="max-width: 100%; height: auto;"></p>
<p>Figure: individual workload factors</p>
<p><img src="bart_files/analysis3b.png" style="max-width: 100%; height: auto;"></p>
<p>Analyses:</p>
<ul>
<li class="fragment">linear mixed models (R, lmer, lmerTest)</li>
<li class="fragment">categorical variable contrasts:
<ul>
<li class="fragment">condition: a two-level variable (0=underload, 1=overload)</li>
<li class="fragment">NASA factors: a six level variable with reference category = physical demands (where we expect no demands, and whatever effect is likely to be non-factor-specific effect of factor)</li>
</ul></li>
<li class="fragment">working memory capacity mean centered</li>
</ul>
<p>1.4 NASA-TLX (weighted)</p>
<pre><code>mod1 = lmer(NASA_weighted ~ condition + (1|subjID), data = data)</code></pre>
<p>PS. it does not converge for (1+condition|subjID)</p>
<pre><code>Fixed effects:
                  Estimate Std. Error     df t value Pr(&gt;|t|)    
(Intercept)         30.662      2.431 70.000   12.61   &lt;2e-16 ***
conditionoverload   55.175      3.439 70.000   16.05   &lt;2e-16 ***</code></pre>
<p>1.4b NASA-TLX (weighted)</p>
<pre><code>mod2 = lmer(NASA_weighted ~ condition * WMC_partial_unit_centered + (1|subjID), data = data)</code></pre>
<p>PS. it does not converge for (1+condition|subjID)</p>
<pre><code>Error: number of observations (=72) &lt;= number of random effects (=72) for term (1 + condition | subjID); the random-effects parameters and the residual variance (or scale parameter) are probably unidentifiable</code></pre>
<pre><code>Fixed effects:
                                            Estimate Std. Error      df t value
(Intercept)                                   30.662      2.454  68.000  12.494
conditionoverload                             55.175      3.471  68.000  15.898
WMC_partial_unit_centered                     -4.940     38.539  68.000  -0.128
conditionoverload:WMC_partial_unit_centered  -27.217     54.502  68.000  -0.499
                                            Pr(&gt;|t|)    
(Intercept)                                   &lt;2e-16 ***
conditionoverload                             &lt;2e-16 ***
WMC_partial_unit_centered                      0.898    
conditionoverload:WMC_partial_unit_centered    0.619  </code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">workload was rated substantially higher (ca. 55 points/100) in the overload activity (go-nogo stroop) than underload activity (contruent stroop)</li>
<li class="fragment">working memory capacity does not moderate this relation (i.e., the workload difference between overload and underload was maintained regardless of working memory capacity),
<ul>
<li class="fragment">however, individual intercept only were used and individual slopes were not included (i.e., the model did not converge towards a solution)</li>
</ul></li>
</ul>
<p>1.5 NASA-TLX factors</p>
<pre><code>mod1 = lmer(score ~ condition * factor + (1+condition|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                          Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)                  9.823      3.366 122.422   2.919  0.00418 ** 
conditionoverload           16.622      4.897 112.315   3.395  0.00095 ***
factor2                     26.593      3.643 350.000   7.301 1.94e-12 ***
factor3                     18.367      3.643 350.000   5.042 7.39e-07 ***
factor4                     20.181      3.643 350.000   5.540 5.94e-08 ***
factor5                     25.647      3.643 350.000   7.041 1.01e-11 ***
factor6                     14.556      3.643 350.000   3.996 7.86e-05 ***
conditionoverload:factor2   36.172      5.151 350.000   7.022 1.14e-11 ***
conditionoverload:factor3   43.424      5.151 350.000   8.430 9.15e-16 ***
conditionoverload:factor4   33.740      5.151 350.000   6.550 2.06e-10 ***
conditionoverload:factor5   31.856      5.151 350.000   6.184 1.74e-09 ***
conditionoverload:factor6   53.416      5.151 350.000  10.369  &lt; 2e-16 ***</code></pre>
<p>1.5b NASA-TLX factors</p>
<pre><code>mod2 = lmer(score ~ condition * factor * WMC_partial_unit_centered + (1+condition|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                                    Estimate Std. Error
(Intercept)                                            9.823      3.401
conditionoverload                                     16.622      4.918
factor2                                               26.593      3.666
factor3                                               18.367      3.666
factor4                                               20.181      3.666
factor5                                               25.647      3.666
factor6                                               14.556      3.666
WMC_partial_unit_centered                             40.849     53.403
conditionoverload:factor2                             36.172      5.185
conditionoverload:factor3                             43.424      5.185
conditionoverload:factor4                             33.740      5.185
conditionoverload:factor5                             31.856      5.185
conditionoverload:factor6                             53.416      5.185
conditionoverload:WMC_partial_unit_centered         -121.529     77.234
factor2:WMC_partial_unit_centered                    -42.177     57.570
factor3:WMC_partial_unit_centered                    -62.910     57.570
factor4:WMC_partial_unit_centered                    -51.729     57.570
factor5:WMC_partial_unit_centered                     10.574     57.570
factor6:WMC_partial_unit_centered                    -60.058     57.570
conditionoverload:factor2:WMC_partial_unit_centered   95.104     81.417
conditionoverload:factor3:WMC_partial_unit_centered  109.806     81.417
conditionoverload:factor4:WMC_partial_unit_centered   60.537     81.417
conditionoverload:factor5:WMC_partial_unit_centered   20.455     81.417
conditionoverload:factor6:WMC_partial_unit_centered  136.812     81.417
                                                          df t value Pr(&gt;|t|)
(Intercept)                                          117.462   2.889  0.00461
conditionoverload                                    109.752   3.380  0.00101
factor2                                              340.000   7.254 2.76e-12
factor3                                              340.000   5.010 8.76e-07
factor4                                              340.000   5.505 7.29e-08
factor5                                              340.000   6.996 1.41e-11
factor6                                              340.000   3.970 8.76e-05
WMC_partial_unit_centered                            117.462   0.765  0.44585
conditionoverload:factor2                            340.000   6.977 1.58e-11
conditionoverload:factor3                            340.000   8.376 1.46e-15
conditionoverload:factor4                            340.000   6.508 2.73e-10
conditionoverload:factor5                            340.000   6.144 2.25e-09
conditionoverload:factor6                            340.000  10.303  &lt; 2e-16
conditionoverload:WMC_partial_unit_centered          109.752  -1.574  0.11848
factor2:WMC_partial_unit_centered                    340.000  -0.733  0.46430
factor3:WMC_partial_unit_centered                    340.000  -1.093  0.27528
factor4:WMC_partial_unit_centered                    340.000  -0.899  0.36954
factor5:WMC_partial_unit_centered                    340.000   0.184  0.85438
factor6:WMC_partial_unit_centered                    340.000  -1.043  0.29760
conditionoverload:factor2:WMC_partial_unit_centered  340.000   1.168  0.24358
conditionoverload:factor3:WMC_partial_unit_centered  340.000   1.349  0.17834
conditionoverload:factor4:WMC_partial_unit_centered  340.000   0.744  0.45766
conditionoverload:factor5:WMC_partial_unit_centered  340.000   0.251  0.80178
conditionoverload:factor6:WMC_partial_unit_centered  340.000   1.680  0.09380
                                                       
(Intercept)                                         ** 
conditionoverload                                   ** 
factor2                                             ***
factor3                                             ***
factor4                                             ***
factor5                                             ***
factor6                                             ***
WMC_partial_unit_centered                              
conditionoverload:factor2                           ***
conditionoverload:factor3                           ***
conditionoverload:factor4                           ***
conditionoverload:factor5                           ***
conditionoverload:factor6                           ***
conditionoverload:WMC_partial_unit_centered            
factor2:WMC_partial_unit_centered                      
factor3:WMC_partial_unit_centered                      
factor4:WMC_partial_unit_centered                      
factor5:WMC_partial_unit_centered                      
factor6:WMC_partial_unit_centered                      
conditionoverload:factor2:WMC_partial_unit_centered    
conditionoverload:factor3:WMC_partial_unit_centered    
conditionoverload:factor4:WMC_partial_unit_centered    
conditionoverload:factor5:WMC_partial_unit_centered    
conditionoverload:factor6:WMC_partial_unit_centered .  </code></pre>
<p>Interpretations</p>
<ul>
<li class="fragment">Physical demands were rated lower than all other factors. But physical demands are not 0 (see intercept ca 9.8/100) liekely reflecting some aspecific effect of workload (i.e., non specific to any factor). This justifies its use as reference category (let’s regress out the effect of physical demands from the other predictors)</li>
<li class="fragment">Physical demands were rated higher for overload than underload (despite in both cases they were sitting at a computer). This might reflect that the aspecific workload was greater for overload than underload. It is not feasible that there were really greater physical demands.</li>
<li class="fragment">The gap between physical demands and each other factor is much greater for overload (ca. 30-50 points / 100)</li>
<li class="fragment">Working memory capacity does not predict or moderate any of the above relationships (i.e., the previous effects) occur regardless of working memory capacity</li>
</ul>
</section>

<section id="objectiveshypotheses-analyses-results-1-cont-1" class="title-slide slide level1 scrollable">
<h1>Objectives/hypotheses, analyses, results #1 cont</h1>
<p>Exploratory analyses:</p>
<ul>
<li class="fragment">The prospects of ending the task sooner would motivate individuals to perform well (relative to other possible motives)</li>
</ul>
<p>TO DO: add figure</p>
<p>List of motives: (TO DO confirm from PsychoPy) “feeling motivated to do well …</p>
<ol type="1">
<li class="fragment">“by the prospects of winning a financial prize”</li>
<li class="fragment">“because I find this activity enjoyable and interesting”</li>
<li class="fragment">“due to my ambition to do the best I can in this activity”</li>
<li class="fragment">“because I enjoy the challenge of this activity”</li>
<li class="fragment">“by the prospects of outperforming other participants”</li>
</ol>
<p>Analysis:</p>
<ul>
<li class="fragment">linear mixed models (R, lmer, lmerTest)</li>
<li class="fragment">categorical variable contrasts:
<ul>
<li class="fragment">condition: a three-level variable (0==underload, 1=overload)</li>
<li class="fragment">motives: a five-level variable with contrasts comparing everything against the first one (temporal incentive, ie: finish sooner)</li>
</ul></li>
</ul>
<pre><code>mod1 &lt;- lmer(motive_value ~ condition * motive + (1+condition|subjID), data = Stroop_longMotive)</code></pre>
<pre><code>Fixed effects:
                          Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)                 58.243      4.958  80.262  11.748  &lt; 2e-16 ***
conditionoverload            9.415      7.330  73.961   1.284 0.203002    
motive2                    -19.077      4.647 280.000  -4.105 5.31e-05 ***
motive3                      4.249      4.647 280.000   0.914 0.361349    
motive4                      5.867      4.647 280.000   1.263 0.207817    
motive5                    -15.702      4.647 280.000  -3.379 0.000831 ***
conditionoverload:motive2   -4.766      6.572 280.000  -0.725 0.468949    
conditionoverload:motive3   -3.875      6.572 280.000  -0.590 0.555964    
conditionoverload:motive4   -8.377      6.572 280.000  -1.275 0.203517    
conditionoverload:motive5   -3.269      6.572 280.000  -0.497 0.619307    </code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">the prospects of ending the task sooner was a substantial source of incentive (see intercept for underload and lack of interaction for lack of evidence of difference in overload)</li>
<li class="fragment">this motive was scored higher than two others (…2…5…) but not others (…3…4…)</li>
<li class="fragment">the condition did not predict or moderate the previous effects (good: in fact, these questions were asked after being explained the adaptive feature but before knowing whether the upcoming activity would be adaptive or not)</li>
</ul>
</section>

<section id="objectiveshypotheses-analyses-results-2" class="title-slide slide level1 scrollable">
<h1>Objectives/hypotheses, analyses, results #2</h1>
<p>Hypothesis driven</p>
<p>2.1 Overload fatigue would be associated with lower accuracy than underload fatigue (only for trial type common to both conditions: congruent go)</p>
<p>Exploratory</p>
<ul>
<li class="fragment">differences in response times and task duration between overload and underload fatigue</li>
<li class="fragment">moderation by working memory capacity</li>
</ul>
<p><img src="bart_files/analysis56.png" style="max-width: 100%; height: auto;"></p>
<p>Analysis:</p>
<ul>
<li class="fragment">linear mixed models (R, lmer, lmerTest)</li>
<li class="fragment">categorical variable contrasts:
<ul>
<li class="fragment">condition: a three-level variable (0==underload, 1=overload)</li>
</ul></li>
<li class="fragment">working memory capacity centered</li>
</ul>
<p>2.1 accuracy</p>
<pre><code>mod1 = lmer(experimentalBlock_Accuracy_congruent_go ~ condition + (1|subjID), data = Stroop_long)</code></pre>
<p>PS. it does not converge for 1+condition|subject</p>
<pre><code>Fixed effects:
                  Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)        92.7850     0.4308  70.0000  215.39   &lt;2e-16 ***
conditionoverload -24.5258     0.6092  70.0000  -40.26   &lt;2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>2.1b accuracy (with working memory capacity as moderator)</p>
<pre><code>mod2 = lmer(experimentalBlock_Accuracy_congruent_go ~ condition * WMC_partial_unit_centered + (1|subjID), data = Stroop_long)</code></pre>
<p>PS. it does not converge for 1+condition|subject</p>
<pre><code>Fixed effects:
                                            Estimate Std. Error       df
(Intercept)                                  92.7850     0.4352  68.0000
conditionoverload                           -24.5258     0.6154  68.0000
WMC_partial_unit_centered                     1.3289     6.8339  68.0000
conditionoverload:WMC_partial_unit_centered  -6.4183     9.6646  68.0000
                                            t value Pr(&gt;|t|)    
(Intercept)                                 213.213   &lt;2e-16 ***
conditionoverload                           -39.851   &lt;2e-16 ***
WMC_partial_unit_centered                     0.194    0.846    
conditionoverload:WMC_partial_unit_centered  -0.664    0.509    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment"><p>analysis 2.1 equivalent to a paired sample t-test</p></li>
<li class="fragment"><p>accuracy for congruent go trials 24.53% higher in underload (93%) than overload. Massive difference in trials that are exactly the same perceptually and expected outcome. the only difference is context whereby in the overload, they had to also evaluate whether the trial was go or nogo, and the trial might have gotten faster over time (to be evaluated below)</p></li>
<li class="fragment"><p>working memory capacity does not moderate the effect (in line with the fact that the difference between over- and underload adjust for each participant and adapt over time to meet their ability and resources)</p></li>
<li class="fragment"><p>Median response times</p></li>
</ul>
<pre><code>mod1 &lt;- lmer(experimentalBlock_MdnRT_congruent_go ~ condition + (1|subjID), data = Stroop_long)</code></pre>
<pre><code>Fixed effects:
                   Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept)        0.516867   0.006345 70.000000  81.455  &lt; 2e-16 ***
conditionoverload  0.043744   0.008974 70.000000   4.875 6.56e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<ul>
<li class="fragment">Median response times (with working memory capacity as moderator)</li>
</ul>
<pre><code>mod2 &lt;- lmer(experimentalBlock_MdnRT_congruent_go ~ condition * WMC_partial_unit_centered + (1|subjID), data = Stroop_long)</code></pre>
<pre><code>Fixed effects:
                                             Estimate Std. Error        df
(Intercept)                                  0.516867   0.006329 68.000000
conditionoverload                            0.043744   0.008951 68.000000
WMC_partial_unit_centered                    0.014554   0.099389 68.000000
conditionoverload:WMC_partial_unit_centered -0.166671   0.140558 68.000000
                                            t value Pr(&gt;|t|)    
(Intercept)                                  81.666  &lt; 2e-16 ***
conditionoverload                             4.887 6.54e-06 ***
WMC_partial_unit_centered                     0.146    0.884    
conditionoverload:WMC_partial_unit_centered  -1.186    0.240    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment"><p>Median response times: ca 516 ms for underload and ca 40 ms slower in overrload –&gt; Overload is adaptive but also more difficult therefore requiring more time</p></li>
<li class="fragment"><p>working memory capacity does not influence this relation (in line with the fact that the difference between over- and underload adjust for each participant and adapt over time to meet their ability and resources)</p></li>
<li class="fragment"><p>Task duration</p></li>
</ul>
<pre><code>mod1 &lt;- lmer(experimentalBlock_duration ~ condition + (1|subjID), data = Stroop_long)</code></pre>
<pre><code>Fixed effects:
                  Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)        1917.29      35.96   69.80  53.324  &lt; 2e-16 ***
conditionoverload  -239.36      49.47   35.00  -4.838 2.61e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<ul>
<li class="fragment">Task duration (with working memory capacity as moderator)</li>
</ul>
<pre><code>mod2 &lt;- lmer(experimentalBlock_duration ~ condition * WMC_partial_unit_centered (1|subjID), data = Stroop_long)</code></pre>
<pre><code>Fixed effects:
                                             Estimate Std. Error        df
(Intercept)                                  0.516867   0.006329 68.000000
conditionoverload                            0.043744   0.008951 68.000000
WMC_partial_unit_centered                    0.014554   0.099389 68.000000
conditionoverload:WMC_partial_unit_centered -0.166671   0.140558 68.000000
                                            t value Pr(&gt;|t|)    
(Intercept)                                  81.666  &lt; 2e-16 ***
conditionoverload                             4.887 6.54e-06 ***
WMC_partial_unit_centered                     0.146    0.884    
conditionoverload:WMC_partial_unit_centered  -1.186    0.240    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">underload activity taking about 1917 seconds, and overload activity about 239 seconds less</li>
<li class="fragment">despite response times for each trial being longer for overload, overall task duration was shorter for overload, suggesting that the adaptive feature makes so there are no “empty” gaps in the trial sequence (expected due to the adaptive pacing)</li>
<li class="fragment">working memory does not moderate this effect (also expected due to individualized and adaptive pacing)</li>
</ul>
</section>

<section id="objectiveshypotheses-analyses-results-2-cont" class="title-slide slide level1 scrollable">
<h1>Objectives/hypotheses, analyses, results #2 cont</h1>
<p>Exploratory: compare accuracy (and response times for go only) for:</p>
<ul>
<li class="fragment">congruent_go</li>
<li class="fragment">incongruent_go</li>
<li class="fragment">congruent_nogo</li>
<li class="fragment">incongruent_nogo</li>
</ul>
<p>TO DO</p>
</section>

<section id="objectiveshypotheses-analyses-results-3" class="title-slide slide level1 scrollable">
<h1>Objectives/hypotheses, analyses, results #3</h1>
<p>Hypothesis driven</p>
<ul>
<li class="fragment">3.1 Mental fatigue induced through computerized activities will increase risk taking behaviour (number of pumps for unexploded balloons)</li>
</ul>
<p>Exploratory:</p>
<ul>
<li class="fragment">3.0 Mental fatigue induced through computerized activities will decrease motivation to perform the decision-making activity.</li>
<li class="fragment">3.2 Mental fatigue induced through computerized activities would alter decision time</li>
<li class="fragment">3.1b and 3.2b working memory capacity could moderate previous effects (e.g., the effect of greater mental fatigue on greater risk-taking would be stronger for individuals with lower working memory capacity)</li>
</ul>
<p>Figure: motives for BART in the three conditions <img src="bart_files/analysis7.png" style="max-width: 100%; height: auto;"></p>
<p>Figure: mean num of pumps for unexploded balloons in the three conditions</p>
<p>TO DO</p>
<p>Figure: decision time for unexploded balloons in the three conditions</p>
<p>TO DO</p>
<p>Analysis:</p>
<ul>
<li class="fragment">linear mixed models (R, lmer, lmerTest)</li>
<li class="fragment">categorical variable contrasts:
<ul>
<li class="fragment">condition: a three-level variable (0=baseline, 1=underload, 2=overload)
<ul>
<li class="fragment">contrast1: -1 1/2 1/2 (average of fatigue vs baseline)</li>
<li class="fragment">contrast2: 0 -1 1 (underload vs overload)</li>
</ul></li>
<li class="fragment">motives: a five-level variable with contrasts comparing everything against the first one (financial incentive)</li>
</ul></li>
<li class="fragment">working memory capacity mean centered</li>
</ul>
<p>3.0 Motives</p>
<pre><code>mod &lt;- lmer(motive_value ~ condition * motive + (1+condition|subjID), data = BART_subjLvl_longMotive)</code></pre>
<pre><code>Fixed effects:
                   Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)         87.3278     2.5733  88.8643  33.936  &lt; 2e-16 ***
condition1          -1.4019     2.8450 202.3823  -0.493 0.622723    
condition2           1.3781     3.0014 100.1281   0.459 0.647123    
motive2            -40.8910     2.5154 420.0005 -16.256  &lt; 2e-16 ***
motive3            -16.5051     2.5154 420.0005  -6.562 1.57e-10 ***
motive4            -20.2672     2.5154 420.0005  -8.057 8.16e-15 ***
motive5            -37.7668     2.5154 420.0005 -15.014  &lt; 2e-16 ***
condition1:motive2 -12.6265     3.5573 420.0005  -3.549 0.000430 ***
condition2:motive2  -2.4807     3.0807 420.0005  -0.805 0.421130    
condition1:motive3  -3.6201     3.5573 420.0005  -1.018 0.309434    
condition2:motive3   0.9995     3.0807 420.0005   0.324 0.745773    
condition1:motive4  -4.9202     3.5573 420.0005  -1.383 0.167356    
condition2:motive4   3.1596     3.0807 420.0005   1.026 0.305665    
condition1:motive5 -12.9009     3.5573 420.0005  -3.627 0.000322 ***
condition2:motive5  -1.2310     3.0807 420.0005  -0.400 0.689676    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">financial motive was strong (ca. 87/100)</li>
<li class="fragment">financial motive was stronger than any other (by 17-41/100 points)</li>
<li class="fragment">no evidence that financial motive differed across conditions</li>
<li class="fragment">however, the relative gaps between financial motive and motives 2 and 5 became even larger when comparing fatigue (average of underload and overload) vs baseline</li>
</ul>
<p>3.1 Risk taking as function of condition (baseline, underload, overload)</p>
<pre><code>mod1 &lt;- lmer(MeanPumps_nonpopped ~ condition + (1|subjID), data = BART_subjLvl_long)</code></pre>
<p>PS. it does not converge for 1+condition|subjID</p>
<pre><code>Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  26.8432     0.5185 35.0000  51.772   &lt;2e-16 ***
condition1    0.5360     0.7232 70.0000   0.741    0.461    
condition2   -0.4511     0.6263 70.0000  -0.720    0.474    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>3.1b same as above but with working memory capacity in the model</p>
<pre><code>mod2 &lt;- lmer(MeanPumps_nonpopped ~ condition * WMC_partial_unit_centered + (1|subjID), data = BART_subjLvl_long)</code></pre>
<p>PS. it does not converge for 1+condition|subjID</p>
<pre><code>Fixed effects:
                                     Estimate Std. Error      df t value
(Intercept)                           26.8432     0.5215 34.0000  51.474
condition1                             0.5360     0.7245 68.0000   0.740
condition2                            -0.4511     0.6274 68.0000  -0.719
WMC_partial_unit_centered              6.3380     8.1893 34.0000   0.774
condition1:WMC_partial_unit_centered  -2.9481    11.3776 68.0000  -0.259
condition2:WMC_partial_unit_centered  12.7339     9.8533 68.0000   1.292
                                     Pr(&gt;|t|)    
(Intercept)                            &lt;2e-16 ***
condition1                              0.462    
condition2                              0.475    
WMC_partial_unit_centered               0.444    
condition1:WMC_partial_unit_centered    0.796    
condition2:WMC_partial_unit_centered    0.201    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations: - on average, participants pump ca. 27 times - no differences across conditions (baseline, underload, overload) - working memory capacity does not predict or moderate effect of condition on mean pumps</p>
<p>3.2 Risk decision time as function of condition (baseline, underload, overload)</p>
<pre><code>mod1 &lt;- lmer(lKey_MdnTimes_nonpopped ~ condition + (1|subjID), data = BART_subjLvl_long)</code></pre>
<p>PS. model does not converge for 1+condition|subjID</p>
<pre><code>Fixed effects:
             Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept) 1.887e-01  1.422e-03 3.500e+01 132.665   &lt;2e-16 ***
condition1  2.234e-03  1.948e-03 7.000e+01   1.147    0.255    
condition2  9.366e-04  1.687e-03 7.000e+01   0.555    0.581    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>3.2b same as above but with working memory capacity in the model</p>
<pre><code>mod2 &lt;- lmer(lKey_MdnTimes_nonpopped ~ condition * WMC_partial_unit_centered + (1|subjID), data = BART_subjLvl_long)</code></pre>
<p>PS. model does not converge for 1+condition|subjID</p>
<pre><code>Fixed effects:
                                       Estimate Std. Error         df t value
(Intercept)                           0.1887137  0.0014278 33.9999946 132.172
condition1                            0.0022337  0.0019343 67.9999919   1.155
condition2                            0.0009366  0.0016752 67.9999919   0.559
WMC_partial_unit_centered             0.0192874  0.0224218 33.9999946   0.860
condition1:WMC_partial_unit_centered -0.0173255  0.0303762 67.9999919  -0.570
condition2:WMC_partial_unit_centered -0.0431242  0.0263065 67.9999919  -1.639
                                     Pr(&gt;|t|)    
(Intercept)                            &lt;2e-16 ***
condition1                              0.252    
condition2                              0.578    
WMC_partial_unit_centered               0.396    
condition1:WMC_partial_unit_centered    0.570    
condition2:WMC_partial_unit_centered    0.106    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations</p>
<ul>
<li class="fragment">decision times are on average ca. 200 ms</li>
<li class="fragment">no evidence that fatigue influeces decision time significantly</li>
</ul>
<p>Exploratory analyes, trial level</p>
<pre><code>mod1 &lt;- lmer(nPumps ~ condition  + (1|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
             Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept)   26.2552     0.5590   35.0504  46.969  &lt; 2e-16 ***
condition1     0.8038     0.1947 3352.5442   4.128 3.74e-05 ***
condition2    -0.4827     0.1704 3352.1111  -2.833  0.00464 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">when considering trial level data, the analysis is more powerful (more sensitive to effects). the analysis converges with both 1|subjID and 1+condition|subjID (i.e., random intercepts only or random intercepts and slopes)</li>
<li class="fragment">for random intercepts (ie, forcing same slope on all participants), there is an effect whereby after fatigue (average of under and overload) participants make 0.8 extra pumps than at baseline; they also make 0.5 pumps more in the underload than overload</li>
</ul>
<pre><code>mod2 &lt;- lmer(nPumps ~ condition  * WMC_partial_unit_centered + (1|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                      Estimate Std. Error        df t value
(Intercept)                            26.2656     0.5631   34.0388  46.649
condition1                              0.8189     0.1939 3350.4228   4.222
condition2                             -0.4834     0.1697 3349.8331  -2.849
WMC_partial_unit_centered               6.1613     8.8359   33.9636   0.697
condition1:WMC_partial_unit_centered   -3.1881     3.0446 3349.8238  -1.047
condition2:WMC_partial_unit_centered   13.9828     2.6134 3348.1887   5.350
                                     Pr(&gt;|t|)    
(Intercept)                           &lt; 2e-16 ***
condition1                           2.48e-05 ***
condition2                            0.00441 ** 
WMC_partial_unit_centered             0.49036    
condition1:WMC_partial_unit_centered  0.29512    
condition2:WMC_partial_unit_centered 9.36e-08 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">working memory capacity does not influence risk taking on its own, but it moderates the under-overload difference in mean pumps, whereby having a higher than average WMC reduces the difference (low-WMC people take more risks in underload than overload, whereas high-WMC people show similar risks across the two conditions)</li>
</ul>
<pre><code>mod3 &lt;- lmer(nPumps ~ condition  * WMC_partial_unit_centered +  (1+condition|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                     Estimate Std. Error      df t value
(Intercept)                           26.7960     0.5217 34.0292  51.359
condition1                             0.5359     0.7821 34.3132   0.685
condition2                            -0.4649     0.5798 34.0272  -0.802
WMC_partial_unit_centered              6.3923     8.1874 33.9506   0.781
condition1:WMC_partial_unit_centered  -2.8465    12.2786 34.2923  -0.232
condition2:WMC_partial_unit_centered  12.8367     9.0931 33.8655   1.412
                                     Pr(&gt;|t|)    
(Intercept)                            &lt;2e-16 ***
condition1                              0.498    
condition2                              0.428    
WMC_partial_unit_centered               0.440    
condition1:WMC_partial_unit_centered    0.818    
condition2:WMC_partial_unit_centered    0.167    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretation:</p>
<ul>
<li class="fragment">However, all previous effects disappear when allowing each subject its own slope across conditions</li>
</ul>
<pre><code>anova(mod1, mod2, mod3)</code></pre>
<pre><code>     npar   AIC   BIC logLik -2*log(L)   Chisq Df Pr(&gt;Chisq)    
mod1    5 23807 23838 -11899     23797                          
mod2    8 23783 23832 -11884     23767  30.114  3  1.306e-06 ***
mod3   13 22822 22902 -11398     22796 970.736  5  &lt; 2.2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretation:</p>
<ul>
<li class="fragment">comparing the three models, mod3 has the best fit</li>
<li class="fragment">the effects shown by mod1 and mod2 are not nonexisting, but they are not consistent across subjects (some take more risks after fatigue, some take less), therefore allowing random slopes removes the effects</li>
<li class="fragment">working memory capacity does not explain the inter-individual variability</li>
</ul>
<pre><code>mod1 &lt;- lmer(lKey_times ~ condition  + (1|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
             Estimate Std. Error        df t value Pr(&gt;|t|)    
(Intercept)  188.7301     1.4694   35.2546 128.439   &lt;2e-16 ***
condition1     1.2588     0.5743 3285.8556   2.192   0.0285 *  
condition2     1.1206     0.5036 3285.1394   2.225   0.0261 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<pre><code>mod2 &lt;- lmer(lKey_times ~ condition  * WMC_partial_unit_centered + (1|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                      Estimate Std. Error        df t value
(Intercept)                           188.6684     1.4772   34.2596 127.718
condition1                              1.2193     0.5710 3283.7293   2.136
condition2                              1.1198     0.5006 3282.9093   2.237
WMC_partial_unit_centered              19.3336    23.1767   34.1527   0.834
condition1:WMC_partial_unit_centered   -4.0294     8.9704 3283.3773  -0.449
condition2:WMC_partial_unit_centered  -49.1269     7.6852 3280.6986  -6.392
                                     Pr(&gt;|t|)    
(Intercept)                           &lt; 2e-16 ***
condition1                             0.0328 *  
condition2                             0.0254 *  
WMC_partial_unit_centered              0.4100    
condition1:WMC_partial_unit_centered   0.6533    
condition2:WMC_partial_unit_centered 1.86e-10 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<pre><code>mod3 &lt;- lmer(lKey_times ~ condition  * WMC_partial_unit_centered + (1+condition|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                                     Estimate Std. Error       df t value
(Intercept)                          188.2314     1.3419  34.0578 140.275
condition1                             1.4489     1.7426  34.6961   0.831
condition2                             0.9348     1.7013  34.1061   0.549
WMC_partial_unit_centered             20.4041    21.0502  33.9319   0.969
condition1:WMC_partial_unit_centered -12.6252    27.3549  34.6666  -0.462
condition2:WMC_partial_unit_centered -47.0954    26.6720  33.8981  -1.766
                                     Pr(&gt;|t|)    
(Intercept)                            &lt;2e-16 ***
condition1                             0.4114    
condition2                             0.5863    
WMC_partial_unit_centered              0.3393    
condition1:WMC_partial_unit_centered   0.6473    
condition2:WMC_partial_unit_centered   0.0864 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<pre><code>     npar   AIC   BIC logLik -2*log(L)   Chisq Df Pr(&gt;Chisq)    
mod1    5 30441 30471 -15215     30431                          
mod2    8 30405 30454 -15195     30389  41.588  3  4.907e-09 ***
mod3   13 29790 29869 -14882     29764 625.566  5  &lt; 2.2e-16 ***</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">mod1 confirms about 200 ms per decision, and ca. 1 ms (not 1 sec as I thought previously!) more when fatigued, and 1 ms more for overload than underload</li>
<li class="fragment">mod2 confirtms the effects are maintained when controlling for WMC, which does not influence decision time but moderated (diminishes) the overload vs underload gap</li>
<li class="fragment">mod3 shows that all effects disappear when allowing random slopes</li>
<li class="fragment">comparing the three models, mod3 has a better fit</li>
</ul>
<p>Even more exploration (just for curiosity)</p>
<pre><code>mod1_quad &lt;- lmer(lKey_times ~ nPumps_c + I(nPumps_c^2) + condition + (1+condition|subjID), data = data)</code></pre>
<pre><code>Fixed effects:
                Estimate Std. Error         df t value Pr(&gt;|t|)    
(Intercept)    1.865e+02  1.344e+00  3.893e+01 138.804  &lt; 2e-16 ***
nPumps_c      -1.600e-02  6.109e-02  3.163e+03  -0.262    0.793    
I(nPumps_c^2)  2.773e-02  4.817e-03  3.291e+03   5.758 9.28e-09 ***
condition1     1.708e+00  1.677e+00  3.555e+01   1.019    0.315    
condition2     8.480e-01  1.712e+00  3.494e+01   0.495    0.623    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
<p>Interpretations:</p>
<ul>
<li class="fragment">median decision time for a balloon is influenced by the number of pumps made for that balloon in a quadratic pattern, whereby deicision times get faster and faster and then slower and slower as a function of number of pumps. this pattern is not influenced by condition</li>
</ul>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 1.0e-2,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>